### ISSUE TITLE
Config works only from common of Advanced template

### ISSUE THREAD

**Issue by dbd5** [ogheo/yii2-htmlcompress#3]
Hi,

Thanks for the work you put into this module.

I've successfully setup the module from the common\config\main\components config file of the advanced template and it does work for both frontend and backend. However, when I run the backend application, it shows a new error with the message "Uncaught SyntaxError: Unexpected end of input". When I turn off the module by setting the config switch off in the config, the error goes away.

To resolve this, I decided to split the config and place the config in both backend\config\main\components config file and frontend\config\main\components file. Somehow, it doesn't work at all when setup this way.
Please advise if I am doing something wrong or if this is a known error.

Regards,

Adam

**Comment by ogheo** [comment]
Hi, I use this module only on frontend and everything work well. Maybe the problem is in your settings. By the way, if you can post somewhere your backend app code, it will be very useful for debugging.

**Comment by ogheo** [comment]
File:
`frontend/config/main.php`  

Code:

```
'components' => [
        'view' => [
            'class' => 'smilemd\htmlcompress\View',
            'compress' => YII_ENV_DEV ? false : true,
        ],
    ],
```

**Comment by dbd5** [comment]
Hi @smilemd ,

It's exactly the same code whether I put it in common, frontend or backend - it goes into the component section of the main config file (main.php - I am using the advanced template)
There are many files, what exactly do you want me to post?

A

**Comment by ogheo** [comment]
Just html output from the browser.
