### ISSUE TITLE
New rexeg breaks JS

### ISSUE THREAD

**Issue by jonazu** [ogheo/yii2-htmlcompress#4]
Hi

You added in you last update a new regex for comments. Unfortunately this breaks my JS code. Example:

```
        // this comment works
        $(document).ready(function () {
            // this comment does not work, regex doesn't catch it
            $('.iCheck').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%'
            });
        });
```

Can you reproduce this issue?

Regards
Jonas

**Comment by ogheo** [comment]
Hi, thank you for report,  i'll take a look.

**Comment by ogheo** [comment]
Can I ask you what you mean with breaks? don't remove them (comments)?

The problem with previous regex was that it may cut some unwanted code and broke entire page. So I decided to remove temporarily this type of comments from regex.

Here is an example of problem: https://regex101.com/r/sK9qY3/1.

If You have a suggestion how to fix it, you are free to make a pull request ;)

**Comment by jonazu** [comment]
The old regex is working well. So I'm just sticking with this one. :-)
