### ISSUE TITLE
New regex breaks url's

### ISSUE THREAD

**Issue by Nuffic** [ogheo/yii2-htmlcompress#8]
Since regex removes everything after //, url's are also removed

**Comment by ogheo** [comment]
Hi @Nuffic,

thanks for your contribution, but new regexp also removes comments from html which is not good.

I've made some test with added cases here: https://regex101.com/r/ijYPvS/1 and all seems good except one case (//blabla.com) but it's ok for me. So if you want, you may add that regex, adapt test cases and I'll merge your request.
